# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf2a2329eeb025f13f46afb94565bb548379aa5edeeb6637d62e27a7478ccf1b044942a0b151a928af2e0c841a29a09c082a443bed490a94dd605ac4e8e4b54c

test:
  secret_key_base: 28f043c9e20e5c6eabb70b004e66b2f1e1f99d2922997fc05e962aa43e90aa49d68b759a6cff2fc48ad329b896450f8c84ccefe026ad359dbd74d40f0df31f47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
